language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
sudo: false
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=dcdb77d8d379ad5f73297b67a0c700887f692f6b301f911cf177394bda32a445 codeclimate-test-reporter < coverage/lcov.info
